#!/bin/bash

# Logging
chunkc core::log_file stdout
chunkc core::log_level warn

# Plugins
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins
chunkc core::hotload 0

# chunkc set custom_bar_enabled            0
# chunkc set custom_bar_all_monitors       0
# chunkc set custom_bar_offset_top         22
# chunkc set custom_bar_offset_bottom      0
# chunkc set custom_bar_offset_left        0
# chunkc set custom_bar_offset_right       0

# Desktop
chunkc set global_desktop_mode           bsp
chunkc set 2_desktop_mode                monocle
chunkc set 3_desktop_mode                float

# Gap
chunkc set global_desktop_offset_top     4
chunkc set global_desktop_offset_bottom  4
chunkc set global_desktop_offset_left    4
chunkc set global_desktop_offset_right   4
chunkc set global_desktop_offset_gap     4
chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

# Binary splitting
chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

# Focus
chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor
chunkc set mouse_follows_focus           off
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1
chunkc set ffm_bypass_modifier           fn
chunkc set ffm_standby_on_float          1

# Border
chunkc set focused_border_color          0xbbffffff
chunkc set focused_border_width          4
chunkc set focused_border_radius         0
chunkc set focused_border_skip_floating  0
chunkc set focused_border_skip_monocle   0

#
# NOTE: these settings require chwm-sa.
#       (https://github.com/koekeishiya/chwm-sa)
#

chunkc set window_float_topmost          0
chunkc set window_fade_inactive          0
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.25
chunkc set window_use_cgs_move           0

# Plugins to load
chunkc core::load border.so
chunkc core::load tiling.so
chunkc core::load ffm.so

# Tiling rules
chunkc tiling::rule --owner Finder --name Copy --state float &
chunkc tiling::rule --owner \"App Store\" --state float
