#!/bin/bash

# Logging
chunkc core::log_file /usr/local/var/log/chunkwm/chunkwm.log
chunkc core::log_level warn

# Plugins
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins
chunkc core::hotload 1

# Desktop
chunkc set global_desktop_mode           bsp
chunkc set 2_desktop_mode                monocle

# Gap
chunkc set global_desktop_offset_top     0
chunkc set global_desktop_offset_bottom  0
chunkc set global_desktop_offset_left    0
chunkc set global_desktop_offset_right   0
chunkc set global_desktop_offset_gap     4

# Binary splitting
chunkc set bsp_spawn_left                0
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

# Focus
chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor
chunkc set mouse_follows_focus           off
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1
chunkc set ffm_bypass_modifier           fn
chunkc set ffm_standby_on_float          1

# Border
chunkc set preselect_border_color        0xff34b044
chunkc set preselect_border_width        4
chunkc set preselect_border_radius       0
chunkc set focused_border_color          0xffd3d0c8
chunkc set focused_border_width          4
chunkc set focused_border_radius         0
chunkc set focused_border_skip_floating  1
chunkc set focused_border_skip_monocle   1

# Load plugins
chunkc core::load border.so
chunkc core::load tiling.so
chunkc core::load ffm.so

# Rules
chunkc tiling::rule --owner Accessibility\ Inspector --state float
chunkc tiling::rule --owner Activity\ Monitor --state float
chunkc tiling::rule --owner App\ Store --state float
chunkc tiling::rule --owner Calendar --state float
chunkc tiling::rule --owner FaceTime --state float
chunkc tiling::rule --owner Finder --state float
chunkc tiling::rule --owner System\ Preferences --state float
chunkc tiling::rule --owner The\ Unarchiver --state float
chunkc tiling::rule --owner Transmission --state float
chunkc tiling::rule --owner WhatsApp --state tile
