#!/usr/bin/env zsh

if [ -z "$1" ]; then
    echo "usage: rmbundle <vim bundle>"
    ls vim/bundle
else
    if ls -A vim/bundle/$1 >&/dev/null; then
        git submodule deinit -f -- vim/bundle/$1 &&
        rm -rf .git/modules/vim/bundle/$1 &&
        git rm -f vim/bundle/$1 &&
        echo "done removing"
    else
        echo "no vim bundle named \"$1\""
    fi
fi
