#!/bin/sh

script_dir="$(realpath "$0" | xargs dirname)"
airpods_mac="$(cat "$script_dir/.airpods.mac")"

# Trigger Hammerspoon to display Airpods battery
open --background "hammerspoon://display-airpods-battery?mac=${airpods_mac}"
