#!/bin/bash

export PATH=/opt/homebrew/bin:$PATH

battery_percent=$(
pmset -g batt | \
grep --extended-regexp --only-matching "\d+%" | \
cut -d % -f 1
)

# 0: Drawing power from AC
# 1: Drawing power from battery
battery_using=$(
pmset -g batt | \
grep --count 'Battery Power'
)

# 0: Battery is not being charged by AC
# 1: Battery is being charged by AC
battery_charging=$(
pmset -g batt | \
grep --count '; charging'
)

wifi_ssid=$(
networksetup -getairportnetwork en0 | \
grep : | \
cut -d : -f 2 | \
cut -c 2-
)

wifi_active=$(
networksetup -getairportpower en0 | \
cut -d : -f 2 | \
cut -c 2- | \
grep --count 'On'
)

bluetooth_active=$(blueutil --power)

bluetooth_device=$(
system_profiler -detailLevel basic -json SPBluetoothDataType 2>/dev/null | \
jq --raw-output --from-file <(cat <<EOF
select(.SPBluetoothDataType[0].devices_list != null)
| .SPBluetoothDataType[0].devices_list
| reduce .[] as \$item ({}; . + \$item)
| to_entries[]
| select(.value.device_connected == "Yes")
| .key
EOF
)
)

cat <<EOF
{
  "battery": {
    "percent": ${battery_percent},
    "using": ${battery_using},
    "charging": ${battery_charging}
  },
  "wifi": {
    "ssid": "${wifi_ssid}",
    "active": ${wifi_active}
  },
  "bluetooth": {
    "device": "${bluetooth_device}",
    "active": ${bluetooth_active}
  }
}
EOF
