#!/bin/sh
# Print out default branch for repository

branches=(master main)

for branch in "${branches[@]}"; do
  git branch | grep --silent "$branch"
  if [[ "$?" == 0 ]]; then
    echo "$branch"
    break
  fi
done
