#!/bin/sh
# Remove specified branch from local and remote

script_dir=$(dirname "$0")

branch="$1"
if [[ -z "$branch" ]]; then
  echo "usage: purge <branch>"
  exit 1
fi

default_branch=$("${script_dir}/default")

git checkout "$default_branch"
git branch --delete --force "$branch"
git push origin ":${branch}"
