#!/bin/sh

script_dir=$(dirname "$0")

default_branch=$("${script_dir}/default")

git checkout "$default_branch"
git pull
git fetch --prune
git branch --verbose | grep '\\[gone\\]' | awk '{print $1}' | xargs git branch --delete --force
