#!/bin/sh

widget_id="widgets-status-index-jsx"

if ! pgrep Übersicht >/dev/null; then
  exit 0
fi

osascript <<EOF
tell application id "tracesOf.Uebersicht" to refresh widget \
  id "${widget_id}"
EOF
