#!/bin/sh

output=$( \
  tmux list-windows -F '#{window_index} #{window_name}' | \
  fzf --tiebreak=index --no-sort
)

if [[ "$?" == 0 ]]; then
  target_window=$(echo "$output" | cut -d ' ' -f 1)
  tmux select-window -t "$target_window"
fi
