#!/bin/bash

output=$( \
  tmux list-windows -F '(#{window_index}) #{window_name}' | sort --version-sort | \
  fzf --tiebreak=index --no-sort
)

if [[ "$?" == 0 ]]; then
  target_window=$(echo "$output" | cut -d ' ' -f 2-)
  tmux select-window -t "$target_window"
fi
