#!/bin/bash

# Kubernetes context and namespace
kube_status=$(
  kubectl config get-contexts --no-headers 2>/dev/null |\
    grep '*' | awk '{ printf "%s/%s", $2, $5 }'
)
if [[ -n "$kube_status" ]]; then
  echo -n "${kube_status}"
fi
