#!/bin/sh

wifi_active=$(
networksetup -getairportpower en0 | \
cut -d : -f 2 | \
cut -c 2- | \
grep --count 'On'
)

if [ "$wifi_active" == 0 ]; then
  networksetup -setairportpower en0 on
  osascript -e 'display notification "Turning on..." with title "Wi-Fi"'
else
  networksetup -setairportpower en0 off
  osascript -e 'display notification "Turning off..." with title "Wi-Fi"'
fi
