#!/bin/sh

bluetooth_active=$(blueutil power)

if [ "$bluetooth_active" == 0 ]; then
  blueutil on
  osascript -e 'display notification "Turning on..." with title "Bluetooth"'
else
  blueutil off
  osascript -e 'display notification "Turning off..." with title "Bluetooth"'
fi
